
development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: dlp_development
  pool: 5
  username: Gabriel
  password:

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: dlp_test
  pool: 5
  username: Gabriel
  password:

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: dlp_production
  pool: 5
  username: Gabriel
  password:
